image: condaforge/mambaforge:23.3.1-0
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - python -V
  - mamba env create -f k4neo.yaml
  - source /opt/conda/bin/activate k4neo
  - poetry install

stages:
  - test
  - test_full

test:
  stage: test
  script:
    - pytest -v --git-aware k4neo/tests/

test_full:
  stage: test_full
  script:
    - pytest --git-aware --symlink --stderr-bytes 100000 tests/
