import os
import sys

configfile: workflow.source_path("../config/config.yaml")
include: "rules/common.smk"

validate_config(config)
if config['modus']['indexing']:
    samples = read_sample_sheet(config['indexing']['samples'])
else:
    samples = pd.DataFrame(columns=['sample', 'bin_id'])

include: "rules/query.smk"
include: "rules/kmindex.smk"
include: "rules/raptor.smk"


rule all:
    input:
        get_final_output()

rule convert_bin_to_fof:
    input:
        sample_sheet = config['query']['index']
    output:
        fof = "index/{wildcards.method}/fof.txt"
    run:
        with open(input.sample_sheet, 'r') as file_handle, open(output.fof, 'w') as write_handle:
            for line in file_handle:
                elements = line.rstrip().split(' : ')
                fastq = elements[1].replace(";", " ")
                write_handle.write(fastq + "\n")
