site_name: k4neo
site_author: Johannes Hausmann
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Input: input.md
  - Output: output.md
  - API reference: api.md
  - References: references.md
  - About: about.md
theme:
  logo: assets/tron.svg
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.tabs
    - toc.integrate
  palette:
    # Palette toggle for light mode 
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode

copyright: © TRON gGmbH, 2026. This work is licensed under MIT.

repo_url: https://github.com/TRON-Private/k4neo
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [..]

markdown_extensions:
  - attr_list
