name: Build and Deploy MkDocs to GitHub Pages

on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
  
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "latest"
      
      - name: Install k4neo
        run: |
          poetry install --with docs

      - name: Trust Git directory
        run: git config --global --add safe.directory "$(pwd)"

      - name: Build MkDocs site
        shell: bash -l {0}
        run: |
          poetry run mkdocs build -f documentation/mkdocs.yaml -d site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: documentation/site

      - name: Deploy to GitHub Pages
        id: deployment

        uses: actions/deploy-pages@v4

